### ISSUE TITLE
TypeError: Cannot handle this data type: (1, 1, 48), |u1

### ISSUE THREAD

**Issue by Kilichbek** [mrlibw/ControlGAN#6]
Hi,
I am getting the following error when running pretrain_DAMSM.py 

Traceback (most recent call last):
  File "pretrain_DAMSM.py", line 270, in <module>
    dataset.ixtoword, image_dir)
  File "pretrain_DAMSM.py", line 124, in train
    ixtoword, attn_maps, att_sze)
  File "/ControlGAN/code/miscc/utils.py", line 144, in build_super_images
    PIL_att = Image.fromarray(np.uint8(one_map))
  File "/.conda/envs/ctrlgan/lib/python3.7/site-packages/PIL/Image.py", line 2753, in fromarray
    raise TypeError("Cannot handle this data type: %s, %s" % typekey) from e
TypeError: Cannot handle this data type: (1, 1, 48), |u1

**Comment by tunakasif** [comment]
As I learned from [ManiGAN](https://github.com/mrlibw/ManiGAN) repo, in lines 128, 256  of [code/miscc/utils.py](https://github.com/mrlibw/ControlGAN/blob/master/code/miscc/utils.py), add `multichannel=True` at the end of the function calls.

Before:
 
```python
one_map = skimage.transform.pyramid_expand(one_map, sigma=20, upscale=vis_size // att_sze)
```

After:

```python
one_map = skimage.transform.pyramid_expand(one_map, sigma=20, upscale=vis_size // att_sze, multichannel=True)
```

**Comment by Kilichbek** [comment]
> As I learned from [ManiGAN](https://github.com/mrlibw/ManiGAN) repo, in lines 128, 256 of [code/miscc/utils.py](https://github.com/mrlibw/ControlGAN/blob/master/code/miscc/utils.py), add `multichannel=True` at the end of the function calls.
> 
> Before:
> 
> ```python
> one_map = skimage.transform.pyramid_expand(one_map, sigma=20, upscale=vis_size // att_sze)
> ```
> 
> After:
> 
> ```python
> one_map = skimage.transform.pyramid_expand(one_map, sigma=20, upscale=vis_size // att_sze, multichannel=True)
> ```

Thank you, @tunakasif. It worked!
